# This is the pre-commit (https://pre-commit.com/) config for our KDD lecture
# Follow the instructions in the README file to get it running
repos:

  # General pre-commit hooks concerning all file types
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
      -   id: check-yaml
      -   id: trailing-whitespace
      -   id: end-of-file-fixer

  # Hooks concerning Latex files
  -   repo: https://github.com/melsigl/latexhooks
      rev: v0.1.1
      hooks:
      -   id: latexindent

  # Hooks concerning Bibtex files
  -   repo: https://github.com/FlamingTempura/bibtex-tidy
      rev: v1.8.5
      hooks:
      -   id: bibtex-tidy

  # Hooks concerning Python files (and Jupyter Notebooks)
  -   repo: https://github.com/psf/black
      rev: 23.1.0
      hooks:
      -   id: black-jupyter

  -   repo: local
      hooks:
        - id: jupyter-nb-clear-output
          name: jupyter-nb-clear-output
          files: \.ipynb$
          stages: [commit]
          language: system
          entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
