import pandas as pd

articles = pd.DataFrame(
    data={
        "AID": range(1, 16),
        "NAME": [
            "Apple",
            "Banana",
            "Kiwi",
            "Clementine",
            "Strawberry",
            "Cherry",
            "Carrot",
            "Bell Pepper",
            "Onion",
            "Salad",
            "Tomato",
            "Cucumber",
            "Spinach",
            "Water Melon",
            "Garlic",
        ],
        "PRICE": [
            0.3,
            0.75,
            0.6,
            0.5,
            0.45,
            0.4,
            0.5,
            0.7,
            0.3,
            0.4,
            0.45,
            0.3,
            0.6,
            1.5,
            0.3,
        ],
        "TYPE": [
            "Fruit",
            "Fruit",
            "Fruit",
            "Fruit",
            "Fruit",
            "Fruit",
            "Vegetable",
            "Vegetable",
            "Vegetable",
            "Vegetable",
            "Vegetable",
            "Vegetable",
            "Vegetable",
            "Fruit",
            "Vegetable",
        ],
    }
)

customers = pd.DataFrame(
    data={
        "CID": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        "NAME": [
            "Alice",
            "Bob",
            "Carol",
            "Dan",
            "Erin",
            "Frank",
            "Grace",
            "Heidi",
            "Ivan",
            "Judy",
        ],
    }
)

customers = pd.DataFrame(
    data={
        "CID": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        "NAME": [
            "Alice",
            "Bob",
            "Carol",
            "Dan",
            "Erin",
            "Frank",
            "Grace",
            "Heidi",
            "Ivan",
            "Judy",
        ],
    }
)

orders = pd.DataFrame(
    data={
        "OID": list(range(1, 11)),
        "CID": [2, 2, 2, 4, 1, 9, 7, 7, 7, 7],
        "DATE": pd.date_range(start="2022-03-25", periods=10),
    }
)

order_positions = pd.DataFrame(
    data={
        "OID": [
            1,
            1,
            1,
            2,
            2,
            2,
            2,
            2,
            3,
            3,
            3,
            3,
            4,
            5,
            5,
            6,
            6,
            6,
            6,
            6,
            7,
            7,
            7,
            7,
            7,
            8,
            8,
            9,
            10,
            10,
        ],
        "AID": [
            15,
            4,
            3,
            9,
            13,
            10,
            6,
            15,
            2,
            2,
            1,
            6,
            3,
            12,
            5,
            2,
            9,
            14,
            3,
            5,
            4,
            1,
            5,
            14,
            2,
            12,
            14,
            1,
            5,
            14,
        ],
        "UNIT": [
            4,
            3,
            11,
            13,
            11,
            1,
            8,
            8,
            6,
            2,
            9,
            17,
            15,
            2,
            18,
            6,
            19,
            14,
            19,
            16,
            6,
            11,
            6,
            9,
            11,
            1,
            7,
            15,
            2,
            9,
        ],
    }
)
