name: Publish Artifacts

on:
  workflow_run:
    workflows: [".github/workflows/push-actions.yml"]
    types:
      - completed
    branches: [artifact-publishing]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Lecture Slides
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow_conclusion: success
          name: Lecture Slides
          path: ./artifacts/lecture
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_run_id: ${{ github.event.workflow_run.id }}

      - name: Download Exercise Archives
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow_conclusion: success
          name: Exercise Archives
          path: ./artifacts/exercise
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_run_id: ${{ github.event.workflow_run.id }}

      - name: Download Submission PDFs
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow_conclusion: success
          name: Submission PDFs
          path: ./artifacts/submission
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_run_id: ${{ github.event.workflow_run.id }}

      - name: Generate index.html
        run: |
          mkdir -p ./artifacts

          # Create main index.html
          cat > ./artifacts/index.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
            <title>KDD Course Materials</title>
            <style>
              body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
              h1 { color: #333; }
              h2 { color: #555; margin-top: 30px; }
              ul { list-style-type: none; padding: 0; }
              li { margin: 10px 0; }
              a { color: #0366d6; text-decoration: none; }
              a:hover { text-decoration: underline; }
              .updated { color: #888; font-size: 0.9em; margin-top: 30px; }
            </style>
          </head>
          <body>
            <h1>KDD Course Materials</h1>

            <h2>Lecture Slides</h2>
            <ul id="lectureList"></ul>

            <h2>Exercise Archives</h2>
            <ul id="exerciseList"></ul>

            <h2>Submission PDFs</h2>
            <ul id="submissionList"></ul>

            <p class="updated">Last updated: <span id="lastUpdated"></span></p>

            <script>
              function generateFileList(directoryPath, elementId, fileExtension) {
                fetch(directoryPath)
                  .then(response => response.text())
                  .then(data => {
                    const parser = new DOMParser();
                    const htmlDoc = parser.parseFromString(data, 'text/html');
                    const links = Array.from(htmlDoc.getElementsByTagName('a'));
                    const files = links
                      .map(link => link.href)
                      .filter(href => href.endsWith(fileExtension))
                      .map(href => href.split('/').pop());

                    const list = document.getElementById(elementId);
                    files.forEach(file => {
                      const item = document.createElement('li');
                      const link = document.createElement('a');
                      link.href = `${directoryPath}/${file}`;
                      link.textContent = file;
                      item.appendChild(link);
                      list.appendChild(item);
                    });
                  })
                  .catch(error => console.error(`Error loading ${directoryPath}:`, error));
              }

              // Generate the file lists
              generateFileList('lecture', 'lectureList', '.pdf');
              generateFileList('exercise', 'exerciseList', '.zip');
              generateFileList('submission', 'submissionList', '.pdf');

              // Update the last updated date
              document.getElementById('lastUpdated').textContent = new Date().toLocaleString();
            </script>
          </body>
          </html>
          EOL

          # Create directory listing files
          for dir in lecture exercise submission; do
            if [ -d "./artifacts/$dir" ]; then
              files=$(find "./artifacts/$dir" -type f | sort)

              cat > "./artifacts/$dir/index.html" << EOL
          <!DOCTYPE html>
          <html>
          <head>
            <title>KDD $dir Files</title>
            <style>
              body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
              h1 { color: #333; }
              ul { list-style-type: none; padding: 0; }
              li { margin: 10px 0; }
              a { color: #0366d6; text-decoration: none; }
              a:hover { text-decoration: underline; }
            </style>
          </head>
          <body>
            <h1>KDD $dir Files</h1>
            <ul>
          EOL

              for file in $files; do
                filename=$(basename "$file")
                echo "    <li><a href=\"$filename\">$filename</a></li>" >> "./artifacts/$dir/index.html"
              done

              cat >> "./artifacts/$dir/index.html" << EOL
            </ul>
            <p><a href="../">Back to main page</a></p>
          </body>
          </html>
          EOL
            fi
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./artifacts
          destination_dir: course-materials
          force_orphan: true
