name: Publish-Artifacts

on:
  workflow_run:
    workflows: [Push-Actions-Test]
    types: [completed]
    branches: [artifact-publishing]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello, world!"
